### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by darsh8200** [alex04072000/SingleHDR#24]
'''bash
!python "E:\\Darsh\\DP\\Internship&Works\\Wielding Helmet\\SingleHDR-master\\training_code\\train_dequantization_net.py" --logdir_path ["E:\\Darsh\\DP\\Internship&Works\\Wielding Helmet\\SingleHDR-master\\weights\\ckpt_deq\\"] --hdr_prefix ["E:\\Darsh\\DP\\Internship&Works\\Wielding Helmet\\SingleHDR_training_data\\HDR-Synth\\"]
'''

' ' '
2021-07-08 12:49:10.036892: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-07-08 12:49:10.036950: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "E:\\Darsh\\DP\\Internship&Works\\Wielding Helmet\\SingleHDR-master\\training_code\\train_dequantization_net.py", line 8, in <module>
    from dataset import get_train_dataset, RandDatasetReader
  File "E:\Darsh\DP\Internship&Works\Wielding Helmet\SingleHDR-master\training_code\dataset.py", line 171, in <module>
    a_dataset_test_posfix_list = _load_pkl('a_dataset_test')
  File "E:\Darsh\DP\Internship&Works\Wielding Helmet\SingleHDR-master\training_code\dataset.py", line 164, in _load_pkl
    with open(os.path.join(CURR_PATH_PREFIX, name + '.pkl'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Darsh\\DP\\Internship&Works\\Wielding Helmet\\SingleHDR-master\\training_code\\a_dataset_test.pkl'
' ' '

**Comment by darsh8200** [comment]
It says a .pkl file is missing when .pkl file is loaded into dataset.py
